### ISSUE TITLE
Macros not working with 5.9.4

### ISSUE THREAD

**Issue by chris-kent** [chris-kent/Live-Input-Macros#1]
Wouter Veeken, can you please enable logging for my plugin, do this in Administration -> Logging and Profiling.
Add a new key "net.kentcom" with ALL
Then add the macros to a page that are not working, refresh the page, edit data or change values.
Then go to your confluence log file, and send me the lines with net.kentcom mentioned.
I hope to get to the bottom of this
Cheers
Chris

**Comment by wveeken** [comment]
```
2016-07-18 10:44:58,924 INFO [ThreadPoolAsyncTaskExecutor::Thread 56] [net.kentcom.MyPluginListener] afterPropertiesSet afterPropertiesSet
2016-07-18 10:44:58,925 INFO [ThreadPoolAsyncTaskExecutor::Thread 56] [net.kentcom.MyPluginListener] getConfluenceDbUrl readConfConfigFile
2016-07-18 10:44:58,977 INFO [ThreadPoolAsyncTaskExecutor::Thread 56] [net.kentcom.MyPluginListener] getConfluenceDbUrl Found filename: /opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-5.1.11.jar
```

**Comment by chris-kent** [comment]
Hi,

This logging is from the plugin startup code. 
I am guessing in that case that the event listener might not be working.
Can you please show me a screen shot of the macros on the page and the url, maybe I can diagnose what is not working from that???
Chris

**Comment by wveeken** [comment]
Hi Chris,

The page URL is http://<intranet-url>/display/~w.veeken/Live+macros<http://%3cintranet-url%3e/display/~w.veeken/Live+macros>

See screenshot below:

[cid:image002.png@01D1E0EA.E94A1310]

Best,

Wouter

**Comment by chris-kent** [comment]
Hi Wouter,
I cannot see the attachment, you may need to attach it using github website, rather than replying via email (if that is how you sent it).

**Comment by wveeken** [comment]
Updated my previous comment.

**Comment by chris-kent** [comment]
Hi,

Unfortunately neither the log or screen helped. I am now installing 5.9.4 to see what it does for me.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi again

I have tested with 5.9.4 and I don't see any issues.

Can you please provide me your browser details and version number. Have you
tried with IE or Chrome.?

Cheers
Chris

**Comment by wveeken** [comment]
I am on Chrome 51.0.2704.103 m. I did not try it on any other browsers.

**Comment by chris-kent** [comment]
Hi Wouter,

I am at a loss then.  I develop on Chrome.  I have been testing my plugin
1.3 on versions right up to 5.10.2 and I am about to mark this version
supported up to the latest version.

The only other option for me to try is to see your system view a Team
Viewer session so I can debug for myself what the issue could be. Let me
know if this is an option for you.

Cheers
Chris

**Comment by wveeken** [comment]
Hi Chris,

That’s probably not a good idea (company laptop/server). Thanks for your help nonetheless. Let me know if you find anything else out.

Best,

Wouter
