### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kevin-decker** [chris-kent/Live-Input-Macros#12]
Hello - I'm looking into your addon for a unique use. We would like to have a page setup in confluence where the fields update as they are modified (which is how i came across your add-on) and I was wondering if this would support something like that. Essentially X user would have the page open using these fields while Y user is looking at it and seeing the information that X user is putting in etc. 

Thank you!
-Kevin

**Comment by chris-kent** [comment]
Hi Kevin,

I had not thought of that, and I believe with a little work I could get that functionality to work.

I have put this on my road map.

Cheers
Chris

**Comment by chris-kent** [comment]
This has been implemented in version 2.2
