### ISSUE TITLE
Error rendering macro 'pulse-button' : null

### ISSUE THREAD

**Issue by SWKRUT** [chris-kent/Live-Input-Macros#13]
Why do I get this error? I am using Confluence 6.4.1.

Thanks,

Steven

**Comment by chris-kent** [comment]
Gi Steven,

Can you please enable logging for the plugin, see
https://kcintegrations.atlassian.net/wiki/spaces/PLUG/pages/187269133/Service+Level+Agreement

and then send me a snip[pet from the log file when the error occurs.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,
If you no longer require support, then I will close this ticket, otherwise please send through a log file so I can diagnose the issue.
Cheers

**Comment by chris-kent** [comment]
I will close this issue if you no longer need support
Cheers
