### ISSUE TITLE
Auto update - International characters in drop downlist forces strange UI update

### ISSUE THREAD

**Issue by PBjernfalk** [chris-kent/Live-Input-Macros#16]
Version 2.2. We have a item in a drop down with Swedish characters (in this case "Björn"). When selecting this item the page is reloaded after a few seconds with the first item in the list. I seems as this is only a UI problem but I'm not sure as the item Björn was in the list and selected before upgrading to 2.2.

**Comment by chris-kent** [comment]
Can you please turn on logging for the plugin, see the documentation, and
send me Confluence log file please. Sounds like it is crashing and not
behaving correctly.

Cheers

**Comment by PBjernfalk** [comment]
Hi,
Attached Confluence log file. I’m not an Confluence expert but hopefully it was enough to change log level to Diagnostic. If not, let me know.

Best Regards/Vänliga Hälsningar
Peter Bjernfalk
Quality Assurance Engineer

**Comment by chris-kent** [comment]
Hi,
There is no attachment, you will need to open github to attach files, can't be done via email replay :(
Cheers

**Comment by PBjernfalk** [comment]
Ok, I hope this works . :-)
[atlassian-confluence.log](https://github.com/chris-kent/Live-Input-Macros/files/2219254/atlassian-confluence.log)

**Comment by PBjernfalk** [comment]
Recording attached. Selecting an item containing Swedish letters (åäö), after a few seconds the selected item is replaced by first item in the drop down.
Not recorded: 
Manually refreshing the page still displays the first item.
cCosing and opening the page again displays correct item for a few seconds.

[LiveInputMacros3.zip](https://github.com/chris-kent/Live-Input-Macros/files/2324072/LiveInputMacros3.zip)

**Comment by chris-kent** [comment]
Hi there,
I have not had a chance to look into this, just trying to get another
plugin version released.
When this is complete I'll come back and look through your logs.
Chris

**Comment by PBjernfalk** [comment]
No hurry, take your time.

Best Regards/Vänliga Hälsningar
Peter Bjernfalk
Quality Assurance Engineer

**Comment by starchaser23** [comment]
I would like to add to this issue - I am expecting the same "auto-selection after a few seconds" also for regular dropdowns with no special characters whatsoever. I have created a new page containing only the dropdown macro with id=1 and three options to select "one", "two", "three". After a few seconds after loading the page, the first option "one" becomes selected.

**Comment by chris-kent** [comment]
Hi,

I have just release version 2.3, which fixes this problem.

Thanks
