### ISSUE TITLE
Live:Table plugin's Save/Trash icons are overlapping

### ISSUE THREAD

**Issue by johnplucas** [chris-kent/Live-Input-Macros#17]
Hello - 

While using the Live:Table plugin sometimes the Save and Trash icons are overlapping, making it impossible to save any table cell updates. 

Any idea on how this is occurring and if there is any type of fix?

Thanks in advance!
John

![image](https://user-images.githubusercontent.com/45183592/48736651-e11e5880-ec19-11e8-845c-a13de2a277e4.png)

**Comment by johnplucas** [comment]
Appreciate it Chris! We will go ahead and use the "Responsive" table setting until you release an update.

Thanks again!
John

**Comment by chris-kent** [comment]
Hi,

This has been fixed in version 2.3.

Cheers
