### ISSUE TITLE
Live:Text Box not saving input when ID contains a space character

### ISSUE THREAD

**Issue by starchaser23** [chris-kent/Live-Input-Macros#18]
We have stumbled upon an issue with the Live:Text Box. If the ID of the Text Box contains a space character (" ") the user can edit its contents, but the saved value in this box is "null". This is especially annoying because after clicking the save (checkmark) button the system seems to save the input. The "null" value becomes visible only after trying to edit the field again or reloading the page.

I suggest including a validation of the ID field while editing the macro or an error message on the page if a macro has a space in their ID. Also, a mention of this in the documentation would be useful :)

**Comment by chris-kent** [comment]
Hi starchaser,

I can see that is a problem, I am working to fix this and you will see the
fix in the next release.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,

I have just release version 2.3, which fixes this problem.

Thanks
