### ISSUE TITLE
POST Call Error With an Empty Live Check Box Macro

### ISSUE THREAD

**Issue by Volk379** [chris-kent/Live-Input-Macros#20]
Hello,

One of our customers noticed that the Live Input Check Box Macro gives a Server Error 500 on a POST call when creating a macro without any labeled choices:
`org.springframework.dao.DataIntegrityViolationException:
Hibernate operation: could not execute statement; sql=n/a; SQL []; 
ORA-01400: cannot insert NULL into ("CONFP"."BANDANA"."BANDANAKEY")
; nested exception is java.sql.SQLIntegrityConstraintViolationException:
ORA-01400: cannot insert NULL into ("CONFP"."BANDANA"."BANDANAKEY")
 at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
caused by: 
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot 
insert NULL into ("CONFP"."BANDANA"."BANDANAKEY")
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) `

This is a bit misleading since the plugin allows an empty checkbox macro to be created from the Confluence GUI without error checking.

**Comment by chris-kent** [comment]
Hi,

I have made a note of this and will rectify this in the next version.

Cheers
Chris

**Comment by chris-kent** [comment]
This has been fixed in version 2.5
Cheers
