### ISSUE TITLE
Live: Table not saving update cell values

### ISSUE THREAD

**Issue by johnplucas** [chris-kent/Live-Input-Macros#21]
Hi Chris!

Our company is really enjoying all of the new macros that come with your Live Macros plugin. It seems like teams are using the Live:Table macro pretty heavily but sometimes run into issues where the table cell data is not updating consistently. Are there any known issues for this type of behavior?

Thanks!
John

**Comment by chris-kent** [comment]
Hi John

I have no known issues.

If you can get some logging for me when this happens that would be great.

I will need logging turned on for the server for the key net.kentcom. But
here is the tricky bit, to get the browser developer tools console log also
when the table fails to work. This last log may not be needed if the server
log gives me the answer.

Actually just start with the server log. Grab a copy of it when the table
save fails and I'll see if that is enough to diagnose the issue

Cheers
Chris

**Comment by johnplucas** [comment]
Hi @chris-kent  - 

The team was not able to replicate the behavior - I will go ahead and close this ticket out. Thanks for the prompt response. Thanks!
