### ISSUE TITLE
Live Table: Not able to update a merged cell

### ISSUE THREAD

**Issue by Volk379** [chris-kent/Live-Input-Macros#22]
**Describe the bug**
A merged cell within a table does not give the option to do a live update

**To Reproduce**
1. Create a table with merged cells and save the page
2. Click on a merged cells to attempt live edit
3. The cell's text will not be editable

**Expected behavior**
The merged cell should be editable through Live Table macro

**Versions (please complete the following information):**
 - Confluence: 6.6.7
 - Plugin: Live Input Macros (Live Table)
 - Data Center: If yes add the Data Center label on the right: No

**Comment by chris-kent** [comment]
Hi,

This is an interesting issue and was not designed with this in mind.

I will need to investigate and try to come up with a solution.

Thanks
Chris

**Comment by chris-kent** [comment]
Hi,

I am trying to debug this to see the issue, and it works for me.
Can you please send through some screen shots of the failure, including screen shots when in edit mode. You will need to attach them using GitHub, email attachments don't work.

Thanks
Chris

**Comment by Volk379** [comment]
> Hi,
> 
> I am trying to debug this to see the issue, and it works for me.
> Can you please send through some screen shots of the failure, including screen shots when in edit mode. You will need to attach them using GitHub, email attachments don't work.
> 
> Thanks
> Chris

Hi Chris,

Thank you for looking into this issue.
After speaking with my team, we can close this as we've moved away from merged cells.

Thank you again for your help :)

Respectfully,
Vasily
