### ISSUE TITLE
broken macro Live: Drop Down List Selector '

### ISSUE THREAD

**Issue by TomasKlima78** [chris-kent/Live-Input-Macros#3]
Hi,
we have a problem with the macro broken Macro Live: Drop Down List Selector '. If you enter in the macro accents (eg. á, ž, č, ř, ...) the macro does not work after the update site to revert back to its original value.
Do you plan to be modified for other languages, so that these characters are permitted?

Cheers
Tomas

**Comment by chris-kent** [comment]
Hi Tomas,

I do apologise for taking so long to look at your request, I have been working on another plugin. I have modified the live-input plugin to handle international chararcters, however I am having troubles testing the plugin. I think it will work but I am not satisfied with the testing I can do on an English OS.

If you don't mind, can you please install the attached jar file (simply rename it from .zip to .jar and manually upload it.)

Then please let me know if this fixes the problem.

I am also keen to know if you find this plugin useful and how I might make it better?

Cheers
Chris
[live-input-macros-1.4.zip](https://github.com/chris-kent/Live-Input-Macros/files/478119/live-input-macros-1.4.zip)

**Comment by TomasKlima78** [comment]
Hi Chris,
I have not heard from him for a long time, I had a vacation.
I tried to upload a new version and it's worse than before. I can not change anything. If I change the information in any macro, and restore the page, everything will return to its original state.
I do not know where it could go wrong

Cheers
Tomas

**Comment by chris-kent** [comment]
Hi Tomas,

I do apologise for the delay, this was very difficult to rectify due to
different browser compatibility and confluence version compatibility.

Please download version 1.5 and let me know if this now works for you.

Cheers

KC Integrations team

**Comment by TomasKlima78** [comment]
Hi Chris,
It has already begun work. Still not working all Czech characters.
These features work: ě č ř ž ů ň ť ď
These characters do not work (when this value is set when you refresh the page returns to the first value): š ý á í é ú

I would like to ask you to explain how it works macro "Reminder".
I can not detect functionality.

Otherwise I am happy with your plugin and would like to use it ...

Cheers
Tomas

**Comment by chris-kent** [comment]
Hi Tomas,

For your first issue, can you please hit F12 in your browser when you select the characters that do not work. View the "Console" in this developer tool and look for errors, either when you select the option or hit page refresh. If there is an error, can you send me a screen shot or grab a copy of the console contents and forward to me.

For the Reminder macro.
It's purpose is to set an alarm for the page. Select a date and time (in the future) and then press Set button. This will set an alarm for the time selected.  The reminder time in the macro editor is a duration before the date/time at which the alarm will go off.  This is a one shot alarm.

When the alarms goes off, it's uses the Confluence Notification system to notify all Watches of the page.

Let me know if this makes sense or if more details are needed.

Cheers
Chris

**Comment by TomasKlima78** [comment]
Hi Chris,
no error occurred, only warnings.
I attach a file
[log.txt](https://github.com/chris-kent/Live-Input-Macros/files/524221/log.txt)

Macro "Reminder" could possibly be solved later, it seems to us that's not working properly ...

Cheers
Tomas

**Comment by chris-kent** [comment]
Hi Tomas,

I really would like to get to the bottom of this so you get the most out of the plugin. At the moment, since I am not bilingual and I only know English, it is difficult for me to understand where the issue is.  Without being able to debug a running system, I will have to ask you to help.

Can you please install the plugin version attached. I have added debugging for the dropdown list macro to try to help me understand what is wrong. Rename the .zip to .jar to install it.

Then, turn on Confluence logging for "net.kentcom" in the admin pages so I get logging from the macro.  Also hit F12 in your browser so I get logging from the browser and do the following for me.

1. Open a page with the Dropdown macro on it.
2. Select a new item from the list, which you know will fail.
3. Refresh the page.
4. then copy the console log from the browser and copy all of the logging from confluence log file with "net.kentcom"

Send me both log files so I can try to understand what is wrong.

Thanks
Chris
[live-input-macros-1.6.zip](https://github.com/chris-kent/Live-Input-Macros/files/533290/live-input-macros-1.6.zip)

**Comment by TomasKlima78** [comment]
Hi Chris,
I set as you requested.
logs join 
[Browser_Log.txt](https://github.com/chris-kent/Live-Input-Macros/files/538924/Browser_Log.txt)
[Confluence_Log.txt](https://github.com/chris-kent/Live-Input-Macros/files/538925/Confluence_Log.txt)



Thanks
Tom

**Comment by chris-kent** [comment]
Hi Tom,

Thanks for that, this does shed a little light on the problem. But the browser log is missing the logging I was expecting, was there any logging after the page finished to load? or can grab the log before a page refresh (the log gets cleared)??

Anyway, what I can see is that the browser gives me the selection š (Selected Data).
Now this does not match any of the Options in the Macro, hence why the page refresh does not show the selection.
Option 1: 0
Option 2: &scaron;
Option 3: 4
Option 4: &aacute;
Option 5: 5
Option 6: è
Option 7: 6

What I need to understand is what is not understanding the language -> the browser or confluence? Maybe you can help here. Which in the above is wrong???  The Selected Data or the Options? Knowing this I might be able to dig a little more.

I am not sure how language works, but have you checked the character encoding on your confluence site? Here is a nice article with some trouble shooting to see if anything in the system is out of sync with encoding, https://confluence.atlassian.com/doc/configuring-character-encoding-174010.html and https://confluence.atlassian.com/doc/troubleshooting-character-encodings-167194.html.

I have not run this, but I'm hoping it might point at my plugin or some other component in your system.

Thanks for your time and I am hoping to get to the bottom of this problem.

By the way, do you use the text box macro?  Does it store your language characters correctly? I am guessing not :(

Cheers
Chris

**Comment by chris-kent** [comment]
Interesting, now that I read the saved message above, I see the browser has translated Option 2 correctly, but the string I get in the Macro is different...  "&scaron;" or "& s c a r o n ;". So it looks like something within confluence, or my plugin does not understand all the international codes?

I'll investigate more tomorrow, but I think the problem is within Confluence or my plugin.?  It would be nice if you could run the troubleshooting above anyway and let me know if the system has any issues identified....

**Comment by chris-kent** [comment]
Hi Tom,

I think I found the bug. I can now select all the characters from your samples above, so I hope this is fixed. Can you please install the attached version, and let me know if OK. If so then I'll put it on the Market Place.
[live-input-macros-1.6.zip](https://github.com/chris-kent/Live-Input-Macros/files/546287/live-input-macros-1.6.zip)

Also, I am keen to find out how I can improve this plugin, so if you have any ideas that would make it better, please let me know.

Cheers
Chris.

**Comment by TomasKlima78** [comment]
Hi Chris,
It seems that it's now OK.

I would also like to return to the macro "Reminder".
It seems that we have also not working properly.
Process:
Select a date and time and then press Set button, but did not occur
When the page F5 set value disappears
The problem will be about the date or time format


2016-10-24 08:57:40,864 INFO [http-nio-443-exec-11] [net.kentcom.liveinput.ReminderServlet] doPost key:45683566-Reminder
2016-10-24 08:57:40,864 INFO [http-nio-443-exec-11] [net.kentcom.liveinput.ReminderServlet] doPost date:24 Oct 2016
2016-10-24 08:57:40,864 INFO [http-nio-443-exec-11] [net.kentcom.liveinput.ReminderServlet] doPost time:8:55 AM
2016-10-24 08:57:40,864 INFO [http-nio-443-exec-11] [net.kentcom.liveinput.ReminderServlet] doPost reminder:0
2016-10-24 08:57:40,864 ERROR [http-nio-443-exec-11] [net.kentcom.liveinput.TimerNotifier] parseDate java.text.ParseException: Unparseable date: "24 Oct 2016T8:55 AM"
 -- referer: https://wiki.finance.homecredit.cz/display/TP/Live+Input+Macros | url: /plugins/servlet/liveinput/reminderServlet | traceId: 6e1b669ebe451962 | userName: tklima
2016-10-24 08:57:40,864 ERROR [http-nio-443-exec-11] [net.kentcom.liveinput.ReminderServlet] doPost Invalid date found in:24 Oct 2016T8:55 AM
 -- referer: https://wiki.finance.homecredit.cz/display/TP/Live+Input+Macros | url: /plugins/servlet/liveinput/reminderServlet | traceId: 6e1b669ebe451962 | userName: tklima
2016-10-24 08:57:44,452 INFO [http-nio-443-exec-9] [net.kentcom.liveinput.ReminderServlet] doPost key:45683566-Reminder
2016-10-24 08:57:44,452 INFO [http-nio-443-exec-9] [net.kentcom.liveinput.ReminderServlet] doPost date:24 Oct 2016
2016-10-24 08:57:44,452 INFO [http-nio-443-exec-9] [net.kentcom.liveinput.ReminderServlet] doPost time:8:55 AM
2016-10-24 08:57:44,452 INFO [http-nio-443-exec-9] [net.kentcom.liveinput.ReminderServlet] doPost reminder:0
2016-10-24 08:57:44,452 ERROR [http-nio-443-exec-9] [net.kentcom.liveinput.TimerNotifier] parseDate java.text.ParseException: Unparseable date: "24 Oct 2016T8:55 AM"
 -- referer: https://wiki.finance.homecredit.cz/display/TP/Live+Input+Macros | url: /plugins/servlet/liveinput/reminderServlet | traceId: 3b41a3b4258a7557 | userName: tklima
2016-10-24 08:57:44,452 ERROR [http-nio-443-exec-9] [net.kentcom.liveinput.ReminderServlet] doPost Invalid date found in:24 Oct 2016T8:55 AM
 -- referer: https://wiki.finance.homecredit.cz/display/TP/Live+Input+Macros | url: /plugins/servlet/liveinput/reminderServlet | traceId: 3b41a3b4258a7557 | userName: tklima

Cheers
Tom

**Comment by chris-kent** [comment]
Hi Tom,

Looks like another language issue, I think I might have the solution, if you could try this new version and let me know if the problem is fixed.

Cheers Chris
[live-input-macros-1.6.zip](https://github.com/chris-kent/Live-Input-Macros/files/550446/live-input-macros-1.6.zip)

**Comment by TomasKlima78** [comment]
Hi Chris,
I tried the new version and does not work, see the excerpt from the log below.

I tried to change the data format to "yyyy.MM.dd HH: mm", and when set in this format works. We use this format "dd.mm.yyyy hh: mm" and this unfortunately does not work

2016-10-26 08:23:38,579 INFO [http-nio-443-exec-28] [net.kentcom.liveinput.ReminderServlet] doPost key:48792932-reminder
2016-10-26 08:23:38,579 INFO [http-nio-443-exec-28] [net.kentcom.liveinput.ReminderServlet] doPost date:2016-10-26
2016-10-26 08:23:38,579 INFO [http-nio-443-exec-28] [net.kentcom.liveinput.ReminderServlet] doPost time:8:25 AM
2016-10-26 08:23:38,579 INFO [http-nio-443-exec-28] [net.kentcom.liveinput.ReminderServlet] doPost reminder:5
2016-10-26 08:23:38,579 ERROR [http-nio-443-exec-28] [net.kentcom.liveinput.TimerNotifier] parseDate java.text.ParseException: Unparseable date: "2016-10-26T8:25 AM"
 -- referer: https://localhost/display/TP/KENT | url: /plugins/servlet/liveinput/reminderServlet | traceId: 5a58e0b58c820dae | userName: tklima
2016-10-26 08:23:38,579 ERROR [http-nio-443-exec-28] [net.kentcom.liveinput.ReminderServlet] doPost Invalid date found in:2016-10-26T8:25 AM
 -- referer: https://localhost/display/TP/KENT | url: /plugins/servlet/liveinput/reminderServlet | traceId: 5a58e0b58c820dae | userName: tklima

Cheers Tom

**Comment by chris-kent** [comment]
Hi Tom,
I am sorry about this, however this is the first time for me to deal with another language other than English.
This next version uses your date locale both on the browser and Java backend, so I hope this fixes the problem. If not I'll need to do more research to understand what is going wrong.
Thanks for your help getting this working on non-English systems.
Cheers
Chris
[live-input-macros-1.6.zip](https://github.com/chris-kent/Live-Input-Macros/files/552843/live-input-macros-1.6.zip)

**Comment by chris-kent** [comment]
Hi Tom,
Have you been able to test the latest version - I'm keen to get this resolved.
Cheers
Chris

**Comment by TomasKlima78** [comment]
Hi Chris,
I've tested so far, it seems to be OK ...
Cheers
Tom
