### ISSUE TITLE
[ENH][Live-Input-Macros] Can we enhance the the live input to become permanent?

### ISSUE THREAD

**Issue by jokr0815** [chris-kent/Live-Input-Macros#5]
Hi,

is there a chance to make it permanent after a user has selected it the first time and cannot change it anymore without the edit button, eg. by introducing a flag changeable?

I would prefer not to see the dropdown anymore in the Page Properties Report.

![not_nice](https://cloud.githubusercontent.com/assets/23552003/24148795/940725d0-0e40-11e7-8170-50a22bb82469.png)

Thanks and br
Jo

**Comment by chris-kent** [comment]
Hi,
I think this may be possible. Let me investigate and get back to you...
Cheers
Chris

**Comment by chris-kent** [comment]
Hi there,

I have implemented this change for 3 macros, Dropdown List, Radio Selection and DatePicker, please grab version 1.8 and let me know what you think.

**Comment by jokr0815** [comment]
Hi @chris-kent 

I love it, though the dropdown in the page status report is maybe no design highlight - maybe there is a way to make it "set once - only text" option, too. But it is absolutely working for my purpose now 🥇 👍 
...the other option is less important...

Especially the sorting function is great.

Thanks a lot for this - have a nice day.
Jo
