### ISSUE TITLE
How to embed selected value?

### ISSUE THREAD

**Issue by gmr** [chris-kent/Live-Input-Macros#7]
I'm trying to figure out how to embed the selected value from the dropdown box in the document. Perhaps I'm misunderstanding the plugin, but my expectation was that if I created a dropdown and named it foo, somehow I could embed text in the confluence page where I would say something like:

```
I like to go {%foo%}
```
And it would replace ``{%foo%}`` with the value selected in the dropdown.

Am I misunderstanding something or just missing something in the macro content?

**Comment by chris-kent** [comment]
Hi,

I am sorry to say that there is no real implementations behind the
checkboxes/radio buttons or dropdowns, other that to allow users to modify
these controls without editing the page. My thoughts were that these
controls would be used in reports or forms, which can simply be changed.

But, now seeing you interpretation of this feature, I could implement a
"substitution" feature, which does what you were expecting. How much value
would this new feature be for you?

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,

I have just release version 2.3, which allows variables to be used on the page for Radio and dropdown inputs.

Thanks
